### ISSUE TITLE
Logging model records

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/dexter#10]
If you have a model instance, and you want to log that, right now you might use `pp`. If you try and pass this to `Lucky.logger.info`, you'll find that nothing happens. No compile error, no output. 

```crystal
# This does nothing
Lucky.logger.info(UserQuery.first)

# This throws an error about undefined method to_json
Lucky.logger.info({record: UserQuery.first})
```

I'm thinking maybe the first way throws a compile-time error, and then we add a special method like `inspect` or whatever to models.

```crystal
# error: If you're trying to log a model, be sure to call #inspect
Lucky.logger.info(UserQuery.first)

Lucky.logger.info(UserQuery.first.inspect)
```

Side related: https://github.com/luckyframework/lucky/issues/950

**Comment by paulcsmith** [comment]
This is no longer an issue in 0.2.0. It will fail if not returning a Hash or NamedTuple, and if you use the built-in `Log` it will call `to_s` on it. Probably best to add a better inspect to models too but I'll close this one for now since the logger side is done

Also we can add a request id in 0.2.0. Working on that this weekend!
